/**
 * AXS AI Creative Studios — shared types
 *
 * Characters are fully synthetic. No uploaded photos of people anywhere.
 * Consistency comes from { seed + description + optional trained LoRA }.
 */

export type StylePreset =
  | "portrait"
  | "cinematic"
  | "editorial"
  | "concept_art"
  | "product"
  | "anime"
  | "raw";

export type ForgeTab =
  | "landing"
  | "studio"
  | "universe"
  | "strategy"
  | "creator"
  | "images"
  | "videos"
  | "voice"
  | "scripts"
  | "campaign"
  | "distribute"
  | "dna"
  | "vault"
  | "analytics"
  | "config"
  | "scene"
  | "billing";

export type AxsWorkflowMode = "worldbuilding" | "directing" | "distribution" | "reading";

export type AxsContentRating = "PG" | "PG-13" | "R" | "X" | "XXX";

export interface BrandVoiceProfile {
  name: string;
  trained: boolean;
  confidence: number;
  tone: string;
  cadence: string;
  audience: string;
  signaturePhrases: string[];
  forbiddenPhrases: string[];
  sampleCount: number;
  lastTrainedAt?: number;
}

/** A synthetic character — the "soul" is a seed + description, not a photo. */
export interface Character {
  id: string;
  name: string;
  age: string;
  heritage: string;
  bodyType: string;
  description: string;         // full free-text description, injected into prompts
  personality: string[];       // tag chips
  styleKeywords: string[];     // visual style tags
  stylePreset: StylePreset;

  /** Deterministic seed used when regenerating this character. */
  seed: number;

  /** Base64 PNG of the character portrait, generated by our own FLUX backend. */
  portraitDataUrl?: string;

  /** Optional filename of a LoRA trained on synthetic outputs, living on RunPod volume. */
  loraName?: string;
  loraWeight?: number;

  createdAt: number;
}

export interface ForgeResult {
  id: string;
  type: "image" | "video";
  /** data:image/png;base64,... or remote URL */
  url: string;
  prompt: string;
  seed?: number;
  characterId?: string;
  stylePreset?: StylePreset;
  width?: number;
  height?: number;
  createdAt: number;
  favorite: boolean;
}

export interface ForgeSettings {
  // Local GPU (ComfyUI)
  useLocalGpu: boolean;
  comfyuiUrl: string;
  comfyuiModel: string;
  comfyuiLoraBase: string;

  // RunPod (cloud fallback)
  runpodApiKey: string;
  runpodEndpointId: string;        // image endpoint
  runpodVideoEndpointId: string;   // optional video endpoint
  elevenLabsApiKey: string;
  openaiApiKey: string;
  googleTtsApiKey: string;
  localVoiceUrl: string;
  voiceEngine: "local" | "elevenlabs" | "openai" | "google";

  // Generation defaults
  stylePreset: StylePreset;
  steps: number;
  guidance: number;
  width: number;
  height: number;
  batchSize: number;
  scheduler: "euler" | "euler_ancestral" | "dpm++" | "heun";
  enhancePrompt: boolean;
  upscaleFactor: number;

  // Character LoRA defaults
  characterLoraWeight: number;

  // Prompts
  defaultNegative: string;

  // Video
  videoDuration: number;
  videoFluidity: number;
  videoFormat: "mp4" | "webm";
  videoResolution: string;
  videoModel: "ltx-video-2.3" | "ltx-video-1.1" | "wan-2.1" | "custom";
  videoWorkflow:
    | "ltx-2.3-character-consistent-directors-cut"
    | "ltx-1.1-rtx-vsr-upscale"
    | "direct"
    | "custom";

  /**
   * FLUX split-model config — required when using unet-only FP8/GGUF FLUX files.
   * These are separate files that live in text_encoders/ and vae/ folders.
   * Leave blank when using a full checkpoint (CLIP+VAE+UNET in one file).
   */
  fluxClipL: string;   // e.g. "clip_l.safetensors"
  fluxT5xxl: string;   // e.g. "t5xxl_fp16.safetensors"
  fluxVae: string;     // e.g. "ae.safetensors"
}

/** Payload the frontend builds and the handler consumes. Mirrors handler.py. */
export interface ImageJobInput {
  prompt: string;
  negative_prompt?: string;
  seed?: number;
  steps?: number;
  guidance?: number;
  width?: number;
  height?: number;
  batch_size?: number;
  scheduler?: ForgeSettings["scheduler"];
  style_preset?: StylePreset;
  enhance_prompt?: boolean;
  character_lora?: string;
  character_lora_weight?: number;
  upscale_factor?: number;
  max_sequence_length?: number;
  /** Multi-LoRA stacking — when provided, takes precedence over character_lora. */
  loras?: Array<{ name: string; weight: number }>;
  /** Face reference image (ComfyUI server filename) for FaceID mode. */
  face_ref_image?: string;
  /** Denoise strength for face reference img2img pass (default 0.88). */
  face_ref_strength?: number;
}

export interface ImageJobOutput {
  status: "success" | "error";
  message?: string;
  images?: Array<{ image: string; mime?: string; seed: number; index: number }>;
  metadata?: Record<string, unknown>;
}

export interface VideoJobInput {
  model?: string;
  workflow?: string;
  prompt: string;
  negative_prompt?: string;
  seed?: number;
  duration_seconds?: number;
  fluidity?: number;
  width?: number;
  height?: number;
  character_lora?: string;
  character_lora_weight?: number;
  format?: "mp4" | "webm";
}

export interface VoiceOverResult {
  id: string;
  title: string;
  script: string;
  engine: ForgeSettings["voiceEngine"];
  voiceId: string;
  voiceName: string;
  audioUrl?: string;
  durationSeconds: number;
  waveform: number[];
  emotions: Record<string, number>;
  createdAt: number;
  status: "ready" | "mock" | "error";
}

export type SubscriptionStatus = "active" | "canceled" | "past_due" | "trialing" | "inactive";

export interface Subscription {
  status: SubscriptionStatus;
  planId: "creator" | "studio" | "empire" | null;
  customerId: string | null;
  subscriptionId: string | null;
  currentPeriodEnd: number | null;
  cancelAtPeriodEnd: boolean;
}
